home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.dashboard, name='dashboard_view'),
    path('test', views.test, name='test' ),
    path('register', views.register, name='register_view' ),
    path('login', views.login, name='login_view' ),
    path('registerUser', views.registerUser, name='registerUser' ),
    path('loginUser', views.loginUser, name='loginUser' ),
    path('logoutUser', views.logoutUser, name='logoutUser'),
    path('resetPassword', views.resetPassword, name="resetPassword_view"),
    path('twostepVerification', views.twostepVerification, name="twostepVerification_view"),
    path('forgotPassword', views.forgotPassword, name="forgotPassword_view"),
    path('verifyEmail', views.verifyEmail, name="verifyEmail_view"),
    path('activatePassword/<uidb64>/<token>', views.activatePassword, name='activatePassword'),
    path('emailVerification/<uidb64>/<token>', views.emailVerification, name='emailVerification'),
    path('insertConnectData', views.insertConnectData, name="insertConnectData"), 
    path('resendEmailVerification', views.resendEmailVerification, name="resendEmailVerification"),
    path('checkConnection', views.checkConnection, name="checkConnection"),
]

wordyAI/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('user/', include('user.urls')),
    path('product/', include('product.urls')),
    path('test/', include('fileuploadtest.urls')),
    path('membership/', include('membership.urls')),
    path('admin_yuriimorigs_qweerrtrtty/', include('superAdmin.urls')),
    path('helpcenter/', include('helpcenter.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from wordyAI.constant import Role

# Create your models here.
class Users(models.Model):
    id = models.BigAutoField(primary_key=True, auto_created= True)
    email = models.CharField(max_length= 50)
    username = models.CharField(max_length=50)
    password = models.CharField(max_length=255)
    email_verification = models.BooleanField()
    avatar = models.ImageField(upload_to='images/')
    firstname = models.CharField(max_length=50)
    lastname = models.CharField(max_length=50)
    gender = models.IntegerField()
    gdpr = models.BooleanField()
    opt_url = models.CharField(max_length=250)
    opt_code = models.CharField(max_length=10)
    activate = models.BooleanField()
    role = models.IntegerField(default=Role.User.value)
    is_first = models.BooleanField(default = True)
    mobile = models.CharField(max_length=50, default='')
    phone = models.CharField(max_length=50, default='')
    address = models.CharField(max_length=50, default='')
    organization = models.CharField(max_length=255, default='')
    zipcode = models.CharField(max_length=50, default = '')
    state = models.CharField(max_length=50, default = '')
    country = models.CharField(max_length=50, default ='')
    language = models.CharField(max_length=50, default = '')
    timezone = models.CharField(max_length=50, default = '')
    currency = models.CharField(max_length=50, default = '')
    company = models.CharField(max_length=50, default = '')
    created_at = models.DateTimeField(auto_now_add = True, null= True)
    updated_at = models.DateTimeField(auto_now = True, null=True)

class ApiData(models.Model):
    id=models.BigAutoField(primary_key=True, auto_created=True)
    datatype = models.IntegerField()
    eshopType = models.IntegerField()
    applicationName = models.CharField(max_length = 255, default= '')
    api_url = models.CharField(max_length = 255)
    consumerKey = models.CharField(max_length = 255)
    consumerToken = models.CharField(max_length = 255)
    activate = models.BooleanField(default = True)
    users = models.ForeignKey(Users, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add = True, null= True)
    updated_at = models.DateTimeField(auto_now = True, null=True)

class OpenaiPrompt(models.Model):
    id=models.BigAutoField(primary_key=True, auto_created=True)
    teaser = models.TextField(default = '', null = True)
    hint = models.TextField(default = '', null = True)
    prompt = models.TextField(default = '', null = True)
    model = models.CharField(max_length = 30, null = True)
    key = models.CharField(max_length = 100, null = True)
    created_at = models.DateTimeField(auto_now_add = True, null= True)
    updated_at = models.DateTimeField(auto_now = True, null=True)
    

home/views.py
from base64 import urlsafe_b64decode, urlsafe_b64encode
from django.shortcuts import render, redirect
from django.contrib.auth.hashers import make_password, check_password
from django.http import JsonResponse
import json
from .models import Users, ApiData
from wordyAI.constant import *
from wordyAI.decorators import *
from .token import account_activation_token
from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_str
from django.core.mail import EmailMessage
from wordyAI.utils import *
from wordyAI.message import *
from woocommerce import API


def test(request):
    uidb64 = urlsafe_b64encode(force_bytes(1))
    print(uidb64)
    uidb64 = b'MQ=='
    uid = force_str(urlsafe_b64decode(uidb64))
    print(uid)
    return JsonResponse({})
# Create your views here.
@login_required
def dashboard(request):
    context = {}
    context = default_context(request, context)
    if request.session.get('is_login') == Role.Admin.value:
        return redirect('superAdmin:dashboard_view')
    else:
        return redirect('dashboard:analytics_view')
    
def register(request):
    context = {}
    return render(request, 'home/register.html', context)

def login(request):
    context = {}
    if 'is_login' in request.session:
        if request.session.get('is_login') == Role.Admin.value:
            return redirect('superAdmin:dashboard_view')
        else:
            return redirect('home:dashboard_view')
    else:
        return render(request, 'home/login.html', context)

def registerUser(request):
    res = {}
    data = json.loads(request.body)
    username = data['username']
    email = data['emailAddress']
    password = data['password']
    user_existance = Users.objects.filter(email = email).exists()

    if user_existance:
        res['message'] = USER_EXIST
        res['status'] = STATUS_FAIL
    else:
        user = Users.objects.create(username = username, email = email, password = make_password(password), activate = True, email_verification = False, gdpr = False, gender = Gender.NONE.value)        
        user.save()
        res['message'] = USER_REGISTER_SUCCESS
        res['status'] = STATUS_SUCCESS
        request.session['email'] = email
    return JsonResponse(res)

def loginUser(request):
    res = {}
    data = json.loads(request.body)
    username = data['username']
    password = data['password']
    rememberMe = data['rememberMe']
    ########## check user existance ###############
    user_existance = Users.objects.filter(username = username, activate = 1).exists()
    if user_existance:
        user = Users.objects.get(username = username)
        res = manipulateLogin(user,password, request)
        if rememberMe :
            request.session.set_expiry(60 * 60 * 24 * 365)
        else:
            request.session.set_expiry(0)
    else:
        res['message'] = USER_NOT_EXIST
        res['status'] = STATUS_FAIL
    
    return JsonResponse(res)

def manipulateLogin(user, password, request):
    res = {}
    if check_password(password, user.password):
        res['message'] = USER_LOGIN_SUCCESS
        res['status'] = STATUS_SUCCESS
        ####### register login  #######
        request.session['email'] = user.email
        request.session['is_login'] = user.role
        if user.role == Role.Admin.value:
            res['url'] = '/admin_yuriimorigs_qweerrtrtty'
        else:
            res['url'] = '/'
    else:
        res['message'] = PASSWORD_NOT_MATCH
        res['status'] = STATUS_FAIL

    return res

def logoutUser(request):
    res = {}
    del request.session['is_login']
    del request.session['email']
    res['message'] = USER_LOGOUT_SUCCESS
    res['status'] = STATUS_SUCCESS
    res['url'] = '/'
    return redirect('home:login_view')

def forgotPassword(request):
    if request.method == 'GET':
        context = {}
        return render(request, 'home/forgotPassword.html', context)
    else:
        res = {}
        data = json.loads(request.body)
        email = data['email']
        user_existance = Users.objects.filter(email = email).exists()
        if user_existance:
            res['message'] = USER_EMAIL_SENT
            res['status'] = STATUS_SUCCESS
            user = Users.objects.get(email = email)
            activatePasswordEmail(request, user, email)
        else:
            res['message'] = USER_NOT_EXIST
            res['status'] = STATUS_FAIL
        return JsonResponse(res)

def resetPassword(request):
    if request.method == 'POST':
        res = {}
        data = json.loads(request.body)
        password = data['password']
        user = Users.objects.get(email = request.session.get('email'))
        user.password = make_password(password)
        user.save()
        res['status'] = STATUS_SUCCESS
        return JsonResponse(res)
    else:
        context = {
            'email': request.session.get('email')
        }
        return render(request, 'home/resetPassword.html', context)

def verifyEmail(request):
    if 'email' in request.session:
        context = {
            'email': request.session.get('email')
        }
        email = request.session.get('email')
        user = Users.objects.get(email = email)
        activateEmailVerification(request, user, email)
        return render(request, 'home/verifyEmail.html', context)
    else:
        return redirect('home:register_view')

def twostepVerification(request):
    context = {}
    context = default_context(request, context)
    return render(request, 'home/twostepVerification.html', context)

def resendEmailVerification(request):
    res = {}
    if 'email' in request.session:
        context = {
            'email': request.session.get('email')
        }
        email = request.session.get('email')
        user = Users.objects.get(email = email)
        activateEmailVerification(request, user, email)
        res['status'] = STATUS_SUCCESS
        res['message'] = USER_EMAIL_SENT
    else:
        res['status'] = STATUS_FAIL
        res['message'] = NOT_REGISTERED_USER

def activateEmailVerification(request, user, to_email):
    print(to_email)
    mail_subject = MAIL_SUBJECT
    message = render_to_string('home/template_email_verification.html', {
        'user': user.username,
        'domain': get_current_site(request).domain,
        'uid': urlsafe_b64encode(force_bytes(user.id)),
        'token': account_activation_token.make_token(user),
        'protocol': 'https' if request.is_secure() else 'http'
    })
    email = EmailMessage(mail_subject, message, to=[to_email])
    email.send()

def activatePasswordEmail(request, user, to_email):
    print(to_email)
    mail_subject = MAIL_SUBJECT
    message = render_to_string('home/template_activate_password.html', {
        'user': user.username,
        'domain': get_current_site(request).domain,
        'uid': urlsafe_b64encode(force_bytes(user.id)),
        'token': account_activation_token.make_token(user),
        'protocol': 'https' if request.is_secure() else 'http'
    })
    email = EmailMessage(mail_subject, message, to=[to_email])
    email.send()

def activatePassword(request, uidb64, token):
    print(uidb64)
    try:
        uid = force_str(urlsafe_b64decode(uidb64[2:-1]))
        user = Users.objects.get(id=uid)
        
    except(TypeError, ValueError, OverflowError, Users.DoesNotExist):
        print('error')
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.save()
        request.session['email'] = user.email
        return redirect('home:resetPassword_view')
    else:
        return redirect('home:forgotPassword_view')
    
def emailVerification(request, uidb64, token):
    print(uidb64)
    try:
        uid = force_str(urlsafe_b64decode(uidb64[2:-1]))
        user = Users.objects.get(id=uid)
        
    except(TypeError, ValueError, OverflowError, Users.DoesNotExist):
        print('error')
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.email_verification = True
        user.save()
        request.session['email'] = user.email
        return redirect('home:login_view')
    else:
        return redirect('home:verifyEmail_view')

def insertConnectData(request):
    res = {}
    data = json.loads(request.body)
    email = request.session.get('email')
    user = Users.objects.get(email=email)
    applicationName = data['applicationName']
    apiUrl = data['apiUrl']
    consumerKey = data['consumerKey']
    consumerToken = data['consumerToken']
    category = data['category']
    eshopType = data['eshopType']

    apiData = ApiData(applicationName = applicationName, api_url = apiUrl, datatype = category, consumerKey = consumerKey,consumerToken = consumerToken, eshopType = eshopType, users = user)
    apiData.save()
    user.is_first = False
    user.save()
    res['status'] = 'success'

    return JsonResponse(res)    

def checkConnection(request):
    res = {}
    data = json.loads(request.body)
    apiUrl = data['apiUrl']
    consumerKey = data['consumerKey']
    consumerToken = data['consumerToken']

    wcapi = API(
        url= apiUrl,
        consumer_key= consumerKey,
        consumer_secret= consumerToken,
        version="wc/v3",
        timeout = 100
    )
    page = 1
    per_page = 1

    try:
        products = wcapi.get("products", params={"page": page, "per_page": per_page}).json()
        res['status'] = STATUS_SUCCESS
    except Exception as e:
        res['status'] = STATUS_FAIL
        res['message'] = INVALID_API
        print('----------------------------------------------------------')
        print(e)
    
    return JsonResponse(res)

templates/home/app.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!--favicon-->
	<link rel="icon" href="{% static 'assets/images/favicon-32x32.png' %}" type="image/png" />
	<!--plugins-->
    
    {% block style %}{% endblock style %}
	<link href="{% static 'assets/plugins/simplebar/css/simplebar.css' %}" rel="stylesheet" />
	<link href="{% static 'assets/plugins/perfect-scrollbar/css/perfect-scrollbar.css' %}" rel="stylesheet" />
	<link href="{% static 'assets/plugins/metismenu/css/metisMenu.min.css' %}" rel="stylesheet" />
	<!-- loader-->
	<link href="{% static 'assets/css/pace.min.css' %}" rel="stylesheet" />
	<script src="{% static 'assets/js/pace.min.js' %}"></script>
	<!-- Bootstrap CSS -->
	<link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/bootstrap-extended.css' %}" rel="stylesheet">
	<link href="{% static 'assets/css/app.css' %}" rel="stylesheet">
	<link href="{% static 'assets/css/icons.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/home.css' %}" rel="stylesheet">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">

    <!-- Theme Style CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/dark-theme.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/semi-dark.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/header-colors.css' %}" />
	<link href="{% static 'assets/css/common.css' %}" rel="stylesheet" />
    <title>wordyAI</title>
</head>

<body>

	<div class="wrapper">
        {% block wrapper %}{% endblock wrapper %}
	</div>
    
	<footer class="page-footer">
		<div class="page-footer-body">
			<p class="mb-0 text-primary ft14 fw600">© 2023 wordyAI | Coded with <span class="text-danger ft20">&#9829;</span> in Europe.</p>
			<p class="mb-0 text-primary ft14 fw600">Imprint | Privacy | Temrs & Conditions | Support</p>
		</div>
	</footer>
	<script src="{% static 'assets/js/bootstrap.bundle.min.js' %}"></script>
	<!--plugins-->
	<script src="{% static 'assets/js/jquery.min.js' %}"></script>
	<script src="{% static 'assets/plugins/simplebar/js/simplebar.min.js' %}"></script>
	<script src="{% static 'assets/plugins/metismenu/js/metisMenu.min.js' %}"></script>
	<script src="{% static 'assets/plugins/perfect-scrollbar/js/perfect-scrollbar.js' %}"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
	<!--app JS-->
	<script src="{% static 'assets/js/app.js' %}"></script>
	<script src="{% static 'assets/js/home.js' %}"></script>
    {% block script %}{% endblock script %}
</body>

</html>

templates/home/forgotPassword.html
{% extends './app.html' %}
{% load static %}

{% block wrapper %}
    <div class="row margin-top-100 mb-5">
        <div class="d-flex flex-row justify-content-center mb-3">
            <img src="{% static 'assets/images/home/wordyAI_logo_final_dark.png' %}" class="register-logo">
        </div>
        <div class="custom-form">
            <form class="row g-3 m-auto needs-validation" id="forgotPasswordForm" novalidate>
                {% csrf_token %}
                <p class="ft24 mb-2 fwbold text-primary">Forgot Password? &nbsp;&#x1F512;</p>
                <label for="register head" class="form-label">Enter your email, and we'll send you instructions to reset your password</label>   
                <div class="col-12">
                    <label for="inputPhoneNo" class="form-label">Email</label>
                    <div class="input-group"> <span class="input-group-text bg-transparent"><i class="bx bxs-message"></i></span>
                        <input type="text" class="form-control border-start-0" id="inputEmail" placeholder="User Email" required>
                    </div>
                    <div class="invalid-feedback">
                        Please insert email address.
                    </div>
                </div>

                <div class="col-12">
                    <div class="d-grid">
                        <button type="btn" class="btn btn-primary px-5" id="loginButton">Send Reset Link</button>
                    </div>
                </div>
                <div class="col-12 text-center">
                    <label class="form-check-label" for="gridCheck2"><a class="text-primary-1 cursor-pointer" href="/login">&lt; Back to log in</a></label>
                </div>
            </form>
        </div> 
    </div>

{% endblock wrapper %}

templates/home/login.html
{% extends './app.html' %}
{% load static %}

{% block wrapper %}
    <div class="row margin-top-100 mb-5">
        <div class="d-flex flex-row justify-content-center mb-3">
            <img src="{% static 'assets/images/home/wordyAI_logo_final_dark.png' %}" class="register-logo">
        </div>
        <div class="custom-form">
            <form class="row g-3 m-auto needs-validation" id="loginForm" novalidate>
                {% csrf_token %}
                <p class="ft24 mb-2 fwbold text-primary">Welcome to wordyAI &nbsp;&#x1F44B;</p>
                <label for="register head" class="form-label ft16">Please sign in to your account and start the adventure</label>   
                <div class="col-12">
                    <label for="inputPhoneNo" class="form-label">Email or Username</label>
                    <div class="input-group"> <span class="input-group-text bg-transparent"><i class="bx bxs-user"></i></span>
                        <input type="text" class="form-control border-start-0" id="inputUsername" placeholder="User Name" required>
                    </div>
                    <div class="invalid-feedback">
                        Please insert email or username.
                    </div>
                </div>
                <div class="col-12">
                    <label for="inputChoosePassword" class="form-label">Password</label>
                    <div class="input-group"> <span class="input-group-text bg-transparent"><i class="bx bxs-lock-open"></i></span>
                        <input type="password" class="form-control border-start-0" id="inputChoosePassword" placeholder="Choose Password" required>
                    </div>
                    <div class="invalid-feedback">
                        Please insert password.
                    </div>
                </div>
                <div class="col-12">
                    <div class="form-check">
                        <div class="d-flex justify-content-between">
                            <div>
                                <input class="form-check-input" type="checkbox" id="rememberMe">
                                <label class="form-check-label" for="gridCheck2">Remember Me</label>
                            </div>
                            <a class="text-primary-1 cursor-pointer" href="/forgotPassword">Forgot Password?</a>
                        </div>
                    </div>
                </div>
                <div class="col-12">
                    <div class="d-grid">
                        <button type="btn" class="btn btn-primary px-5" id="loginButton">Sign in</button>
                    </div>
                </div>
                <div class="col-12 text-center">
                    <label class="form-check-label" for="gridCheck2">New on our platform? <a class="text-primary-1 cursor-pointer" href="/register">Create an account</a></label>
                </div>
                <div class="col-12 text-center">
                    <label class="form-check-label" for="gridCheck2">or</label>
                </div>
                <hr>
                <div class="col-12 text-center">
                    <button type="button" class="btn btn-warning"><i class="bx bxl-facebook me-0"></i>
                    </button>
                    <button type="button" class="btn btn-info"><i class="bx bxl-twitter me-0"></i>
                    </button>
                    <button type="button" class="btn btn-danger"><i class="bx bxl-google me-0"></i>
                    </button>
                </div>
            </form>
        </div>
    </div>

{% endblock wrapper %}

templates/home/register.html
{% extends './app.html' %}
{% load static %}

{% block wrapper %}
    <div class="row margin-top-100 mb-5">
        <div class="d-flex flex-row justify-content-center mb-3">
            <img src="{% static 'assets/images/home/wordyAI_logo_final_dark.png' %}" class="register-logo">
        </div>
        <div class="custom-form">
            <form class="row g-3 m-auto needs-validation" id="registerForm" novalidate>
                {% csrf_token %}
                <p class="ft24 mb-2 fwbold text-primary">Adventure starts here &nbsp;&#x1f680;</p>
                <label for="register head" class="form-label ft16">Take your online store to the next level!</label>   
                <div class="col-12">
                    <label for="inputPhoneNo" class="form-label">Username</label>
                    <div class="input-group"> <span class="input-group-text bg-transparent"><i class="bx bxs-user"></i></span>
                        <input type="text" class="form-control border-start-0" id="inputUsername" placeholder="User Name" required>
                    </div>
                    <div class="invalid-feedback">
                        Please insert username.
                    </div>
                </div>
                <div class="col-12">
                    <label for="inputEmailAddress" class="form-label">Email Address</label>
                    <div class="input-group"> <span class="input-group-text bg-transparent"><i class="bx bxs-message"></i></span>
                        <input type="text" class="form-control border-start-0" id="inputEmailAddress" placeholder="Email Address" required>
                    </div>
                    <div class="invalid-feedback">
                        Please insert email address.
                    </div>
                </div>
                <div class="col-12">
                    <label for="inputChoosePassword" class="form-label">Choose Password</label>
                    <div class="input-group"> <span class="input-group-text bg-transparent"><i class="bx bxs-lock-open"></i></span>
                        <input type="password" class="form-control border-start-0" id="inputChoosePassword" placeholder="Choose Password" required>
                    </div>
                    <div class="invalid-feedback">
                        Please insert password.
                    </div>
                </div>
                <div class="col-12">
                    <label for="inputConfirmPassword" class="form-label">Confirm Password</label>
                    <div class="input-group"> <span class="input-group-text bg-transparent"><i class="bx bxs-lock"></i></span>
                        <input type="password" class="form-control border-start-0" id="inputConfirmPassword" placeholder="Confirm Password" required>
                    </div>
                    <div class="invalid-feedback">
                        Please insert confirm password.
                    </div>
                </div>
                <div class="col-12">
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" id="gridCheck2" required>
                        <label class="form-check-label" for="gridCheck2">I agree to <a class="text-primary-1 cursor-pointer" href="">privacy policy & terms</a></label>
                    </div>
                </div>
                <div class="col-12">
                    <div class="d-grid">
                        <button type="btn" class="btn btn-primary px-5" id="registerButton">Register</button>
                    </div>
                </div>
                <div class="col-12 text-center">
                    <label class="form-check-label" for="gridCheck2">Already have an account? <a class="text-primary-1 cursor-pointer" href="/login">Sign in instead</a></label>
                </div>
                <div class="col-12 text-center">
                    <label class="form-check-label" for="gridCheck2">or</label>
                </div>
                <hr>
                <div class="col-12 text-center">
                    <button type="button" class="btn btn-warning"><i class="bx bxl-facebook me-0"></i>
                    </button>
                    <button type="button" class="btn btn-info"><i class="bx bxl-twitter me-0"></i>
                    </button>
                    <button type="button" class="btn btn-danger"><i class="bx bxl-google me-0"></i>
                    </button>
                </div>
            </form>
        </div>
    </div>

{% endblock wrapper %}

templates/home/resetPassword.html
{% extends './app.html' %}
{% load static %}

{% block wrapper %}
    <div class="row margin-top-100 mb-5">
        <div class="d-flex flex-row justify-content-center mb-3">
            <img src="{% static 'assets/images/home/wordyAI_logo_final_dark.png' %}" class="register-logo">
        </div>
        <div class="custom-form">
            <form class="row g-3 m-auto needs-validation" id="resetPasswordForm" novalidate>
                {% csrf_token %}
                <p class="ft24 mb-2 fwbold text-primary">Reset Password &nbsp;&#x1F512;</p>
                <label for="register head" class="form-label ft16">for {{ email }}</label>   
                <div class="col-12">
                    <label for="inputChoosePassword" class="form-label">New Password</label>
                    <div class="input-group"> <span class="input-group-text bg-transparent"><i class="bx bxs-lock-open"></i></span>
                        <input type="password" class="form-control border-start-0" id="inputChoosePassword" placeholder="Choose Password" required>
                    </div>
                    <div class="invalid-feedback">
                        Please insert password.
                    </div>
                </div>
                <div class="col-12">
                    <label for="inputConfirmPassword" class="form-label">Confirm Password</label>
                    <div class="input-group"> <span class="input-group-text bg-transparent"><i class="bx bxs-lock"></i></span>
                        <input type="password" class="form-control border-start-0" id="inputConfirmPassword" placeholder="Confirm Password" required>
                    </div>
                    <div class="invalid-feedback">
                        Please insert confirm password.
                    </div>
                </div>
                <div class="col-12">
                    <div class="d-grid">
                        <button type="btn" class="btn btn-primary px-5" id="loginButton">Set New Password</button>
                    </div>
                </div>
                <div class="col-12 text-center">
                    <label class="form-check-label" for="gridCheck2"><a class="text-primary-1 cursor-pointer" href="/login">&lt; Back to log in</a></label>
                </div>

            </form>
        </div>
    </div>

{% endblock wrapper %}

templates/home/template_activate_password.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:

http://{{ domain }}{% url 'home:activatePassword' uidb64=uid token=token %}
{% endautoescape %}

templates/home/template_email_verification.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:

http://{{ domain }}{% url 'home:emailVerification' uidb64=uid token=token %}
{% endautoescape %}

templates/home/verifyEmail.html
{% extends './app.html' %}
{% load static %}

{% block wrapper %}
    <div class="row margin-top-100 mb-5">
        <div class="d-flex flex-row justify-content-center mb-3">
            <img src="{% static 'assets/images/home/wordyAI_logo_final_dark.png' %}" class="register-logo">
        </div>
        <div class="custom-form">
            <form class="row g-3 m-auto needs-validation" id="verifyEmailForm" novalidate>
                {% csrf_token %}
                <p class="ft24 mb-2 fwbold text-primary">Verify your email &nbsp;&#x2709;</p>
                <label for="register head" class="form-label ft16">Account activation link sent to your email address: {{ email }} Please follow the link inside to continue.</label>   
                <div class="col-12">
                    <div class="d-grid">
                        <button type="btn" class="btn btn-primary px-5" id="loginButton">Skip for now</button>
                    </div>
                </div>
                <div class="col-12 text-center">
                    <label class="form-check-label" for="gridCheck2">Didn't get the mail? <b class="text-primary-1 cursor-pointer" id="resendEmail">Resend</b></label>
                </div>
            </form>
        </div>
    </div>

{% endblock wrapper %}