dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'
urlpatterns = [
    path('analytics', views.analytics, name='analytics_view'),
    path('test', views.test, name='test_view'),
 
]

helpcenter/urls.py
from django.urls import path
from . import views

app_name = 'helpcenter'
urlpatterns = [
    path('', views.index, name='index_view'),
    path('get_category_data', views.get_category_data, name="get_category_data"),
    path('delete_category', views.delete_category, name="delete_category"),
    path('edit_category', views.edit_category, name="edit_category"),
    path('update_category', views.update_category, name="update_category"),
    path('delete_category_bulk', views.delete_category_bulk, name="delete_category_bulk"),
    path('get_content_data', views.get_content_data, name="get_content_data"),
    path('delete_content', views.delete_content, name="delete_content"),
    path('edit_content', views.edit_content, name="edit_content"),
    path('update_content', views.update_content, name="update_content"),
    path('delete_content_bulk', views.delete_content_bulk, name="delete_content_bulk"),
    path('change_audience', views.change_audience, name="change_audience"),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.dashboard, name='dashboard_view'),
    path('test', views.test, name='test' ),
    path('register', views.register, name='register_view' ),
    path('login', views.login, name='login_view' ),
    path('registerUser', views.registerUser, name='registerUser' ),
    path('loginUser', views.loginUser, name='loginUser' ),
    path('logoutUser', views.logoutUser, name='logoutUser'),
    path('resetPassword', views.resetPassword, name="resetPassword_view"),
    path('twostepVerification', views.twostepVerification, name="twostepVerification_view"),
    path('forgotPassword', views.forgotPassword, name="forgotPassword_view"),
    path('verifyEmail', views.verifyEmail, name="verifyEmail_view"),
    path('activatePassword/<uidb64>/<token>', views.activatePassword, name='activatePassword'),
    path('emailVerification/<uidb64>/<token>', views.emailVerification, name='emailVerification'),
    path('insertConnectData', views.insertConnectData, name="insertConnectData"), 
    path('resendEmailVerification', views.resendEmailVerification, name="resendEmailVerification"),
    path('checkConnection', views.checkConnection, name="checkConnection"),
]

product/urls.py
from django.urls import path
from . import views

app_name = 'product'
urlpatterns = [
    path('product', views.product, name='product_view'),
    path('getStockData', views.getStockData, name='getStockData'),
    path('getCategoryData', views.getCategoryData, name='getCategoryData'),
    path('getProductData', views.getProductData, name='getProductData'),
    path('getProductDataById', views.getProductDataById, name='getProductDataById'),
    path('detail/<product_id>', views.product_detail, name='product_detail_view'),
    path('productOptimize', views.productOptimize, name='product_optimze'),
    path('productDownloadStart', views.productDownloadStart, name='product_download_start'),
    path('productDownloadStop', views.productDownloadStop, name='product_download_stop'),
    path('productDownloadStatus', views.productDownloadStatus, name='product_download_status'),
    path('saveProductDetail', views.saveProductDetail, name='save_product_detail'),
    path('getProductStatus', views.getProductStatus, name='get_product_status'),
    path('productPush', views.productPush, name='product_push'),
    path('productUploadStart', views.productUploadStart, name='product_upload_start'),
    path('productUploadStop', views.productUploadStop, name='product_upload_stop'),
    path('productUploadStatus', views.productUploadStatus, name='product_upload_status'),
    path('productOptimizeStart', views.productOptimizeStart, name='product_optimize_start'),
    path('productOptimizeStop', views.productOptimizeStop, name='product_optimize_stop'),
    path('productOptimizeStatus', views.productOptimizeStatus, name='product_optimize_status'),
    path('checkThreadStatus', views.checkThreadStatus, name='check_thread_status'),
    path('test', views.test, name='test'),
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
    path('profile', views.profile, name='profile_view'),
    path('billing', views.billing, name='billing_view'),
    path('notification', views.notification, name='notification_view'),
    path('connections', views.connections, name='connections_view'),
    path('saveProfile', views.saveProfile, name='saveProfile'),
    path('security', views.security, name='security_view'),
    path('deactivate_account', views.deactivate_account, name='deactivate_account'),
    path('update_password', views.update_password, name='update_password'),
    path('admin/get_users', views.get_users, name='admin_get_users'),
    path('check_connection', views.check_connection, name='check_connection'),
    path('edit_shop', views.edit_shop, name='edit_shop'),
    path('update_shop', views.update_shop, name='update_shop'),
]

wordyAI/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('user/', include('user.urls')),
    path('product/', include('product.urls')),
    path('test/', include('fileuploadtest.urls')),
    path('membership/', include('membership.urls')),
    path('admin_yuriimorigs_qweerrtrtty/', include('superAdmin.urls')),
    path('helpcenter/', include('helpcenter.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/layouts/app.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!--favicon-->
	<link rel="icon" href="{% static 'assets/images/favicon-32x32.png' %}" type="image/png" />
	<!--plugins-->
    
    {% block style %}{% endblock style %}
	<link href="{% static 'assets/plugins/simplebar/css/simplebar.css' %}" rel="stylesheet" />
	<link href="{% static 'assets/plugins/perfect-scrollbar/css/perfect-scrollbar.css' %}" rel="stylesheet" />
	<link href="{% static 'assets/plugins/metismenu/css/metisMenu.min.css' %}" rel="stylesheet" />
	<!-- loader-->
	<link href="{% static 'assets/css/pace.min.css' %}" rel="stylesheet" />
	<script src="{% static 'assets/js/pace.min.js' %}"></script>
	<!-- Bootstrap CSS -->
	<link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/bootstrap-extended.css' %}" rel="stylesheet">
	<link href="{% static 'assets/css/app.css' %}" rel="stylesheet">
	<link href="{% static 'assets/css/icons.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">

    <!-- Theme Style CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/dark-theme.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/semi-dark.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/header-colors.css' %}" />
    <title>wordyAI</title>
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-XT2X5DD3QX"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'G-XT2X5DD3QX');
        gtag("event", "CustomEvent", {
            menu_item_name: "Hello, this is custome event test",
            menu_item_url: "hello.co",
        });
    </script>
</head>

<body>
	<!--wrapper-->
	<div class="wrapper">
        <!--navigation-->
        {% include 'layouts/nav.html' %}
        <!--end navigation-->
        
		<!--start header -->
		{% include 'layouts/header.html' %}
		<!--end header -->
		
		<!--start page wrapper -->
        {% block wrapper %}{% endblock wrapper %}
		<!--end page wrapper -->
		<!--start overlay-->
		<div class="overlay toggle-icon"></div>
		<!--end overlay-->
		<!--Start Back To Top Button--> <a href="javaScript:;" class="back-to-top"><i class='bx bxs-up-arrow-alt'></i></a>
		<!--End Back To Top Button-->
		<footer class="page-footer">
            <div class="page-footer-body">
                <p class="mb-0 text-primary ft14 fw600">© 2023 wordyAI | Coded with <span class="text-danger ft20">&#9829;</span> in Europe.</p>
                <p class="mb-0 text-primary ft14 fw600">Imprint | Privacy | Temrs & Conditions | Documentation | Support</p>
            </div>
		</footer>
	</div>
    
	<!--end wrapper-->
    <!--start switcher-->
    {% comment %} <div class="switcher-wrapper">
        <div class="switcher-btn"> <i class='bx bx-cog bx-spin'></i>
        </div>
        <div class="switcher-body">
            <div class="d-flex align-items-center">
                <h5 class="mb-0 text-uppercase">Theme Customizer</h5>
                <button type="button" class="btn-close ms-auto close-switcher" aria-label="Close"></button>
            </div>
            <hr/>
            <h6 class="mb-0">Theme Styles</h6>
            <hr/>
            <div class="d-flex align-items-center justify-content-between">
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="flexRadioDefault" id="lightmode" checked>
                    <label class="form-check-label" for="lightmode">Light</label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="flexRadioDefault" id="darkmode">
                    <label class="form-check-label" for="darkmode">Dark</label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="flexRadioDefault" id="semidark">
                    <label class="form-check-label" for="semidark">Semi Dark</label>
                </div>
            </div>
            <hr/>
            <div class="form-check">
                <input class="form-check-input" type="radio" id="minimaltheme" name="flexRadioDefault">
                <label class="form-check-label" for="minimaltheme">Minimal Theme</label>
            </div>
            <hr/>
            <h6 class="mb-0">Header Colors</h6>
            <hr/>
            <div class="header-colors-indigators">
                <div class="row row-cols-auto g-3">
                    <div class="col">
                        <div class="indigator headercolor1" id="headercolor1"></div>
                    </div>
                    <div class="col">
                        <div class="indigator headercolor2" id="headercolor2"></div>
                    </div>
                    <div class="col">
                        <div class="indigator headercolor3" id="headercolor3"></div>
                    </div>
                    <div class="col">
                        <div class="indigator headercolor4" id="headercolor4"></div>
                    </div>
                    <div class="col">
                        <div class="indigator headercolor5" id="headercolor5"></div>
                    </div>
                    <div class="col">
                        <div class="indigator headercolor6" id="headercolor6"></div>
                    </div>
                    <div class="col">
                        <div class="indigator headercolor7" id="headercolor7"></div>
                    </div>
                    <div class="col">
                        <div class="indigator headercolor8" id="headercolor8"></div>
                    </div>
                </div>
            </div>
            <hr/>
            <h6 class="mb-0">Sidebar Colors</h6>
            <hr/>
            <div class="header-colors-indigators">
                <div class="row row-cols-auto g-3">
                    <div class="col">
                        <div class="indigator sidebarcolor1" id="sidebarcolor1"></div>
                    </div>
                    <div class="col">
                        <div class="indigator sidebarcolor2" id="sidebarcolor2"></div>
                    </div>
                    <div class="col">
                        <div class="indigator sidebarcolor3" id="sidebarcolor3"></div>
                    </div>
                    <div class="col">
                        <div class="indigator sidebarcolor4" id="sidebarcolor4"></div>
                    </div>
                    <div class="col">
                        <div class="indigator sidebarcolor5" id="sidebarcolor5"></div>
                    </div>
                    <div class="col">
                        <div class="indigator sidebarcolor6" id="sidebarcolor6"></div>
                    </div>
                    <div class="col">
                        <div class="indigator sidebarcolor7" id="sidebarcolor7"></div>
                    </div>
                    <div class="col">
                        <div class="indigator sidebarcolor8" id="sidebarcolor8"></div>
                    </div>
                </div>
            </div>
        </div>
    </div> {% endcomment %}
    <!--end switcher-->
	<!-- Bootstrap JS -->
    
	<script src="{% static 'assets/js/bootstrap.bundle.min.js' %}"></script>
	<!--plugins-->
	<script src="{% static 'assets/js/jquery.min.js' %}"></script>
	<script src="{% static 'assets/plugins/simplebar/js/simplebar.min.js' %}"></script>
	<script src="{% static 'assets/plugins/metismenu/js/metisMenu.min.js' %}"></script>
	<script src="{% static 'assets/plugins/perfect-scrollbar/js/perfect-scrollbar.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
	<!--app JS-->
	<script src="{% static 'assets/js/app.js' %}"></script>
    <script src="{% static 'assets/js/sidebar.js' %}"></script>
    {% block script %}{% endblock script %}
</body>

</html>

templates/layouts/nav.html
{% load static %}
<div class="sidebar-wrapper" data-simplebar="true">
    <div class="sidebar-header">
        <div>
            <img src="{% static 'assets/images/home/wordyAI_logo_small_final_white.png' %}" class="logo-icon" alt="logo icon">
        </div>
        <div>
            <h4 class="logo-text">wordyAI</h4>
        </div>
        <div class="ms-auto">
            <img class="toggle-icon-hide" src="{% static 'assets/images/dashboard/hide-navbar-icon.png' %}">
            <img class="toggle-icon-show" src="{% static 'assets/images/dashboard/show-navbar-icon.png' %}">
        </div>
    </div>
    <div class="d-flex flex-column sidebar-body">
        <div class="navbar-wrapper">
            <div class="navbar-item-wrapper">
                <div class="navbar-item-prev">
                </div>
            </div>
            <a href="{% url 'dashboard:analytics_view' %}" class="navbar-item-body">
                <div class="navbar-item-icon"><i class='bx bx-home'></i>
                </div>
                <p class="navbar-item-content">Dashboard</p>
            </a>
            <div class="navbar-item-wrapper">
                <div class="navbar-item-prev">
                </div>
            </div>
            <a href="{% url 'product:product_view' %}" class="navbar-item-body">
                <div class="navbar-item-icon"><i class='bx bxs-cube-alt'></i>
                </div>
                <p class="navbar-item-content">Product</p>
            </a>
            <div class="navbar-item-wrapper">
                <div class="navbar-item-prev">
                </div>
            </div>
            <a href="{% url 'membership:billing_view' %}" class="navbar-item-body">
                <div class="navbar-item-icon"><i class='bx bxs-user'></i>
                </div>
                <p class="navbar-item-content">Membership</p>
            </a>
            <div class="navbar-item-wrapper">
                <div class="navbar-item-prev">
                </div>
            </div>
            <a href="{% url 'helpcenter:index_view' %}" class="navbar-item-body">
                <div class="navbar-item-icon"><i class='bx bx-help-circle'></i>
                </div>
                <p class="navbar-item-content">Help Center</p>
            </a>
            <div class="navbar-item-wrapper">
                <div class="navbar-item-prev">
                </div>
            </div>
            <a href="{% url 'user:profile_view' %}" class="navbar-item-body">
                <div class="navbar-item-icon"><i class='bx bx-cog'></i>
                </div>
                <p class="navbar-item-content">Settings</p>
            </a>
            <div class="navbar-item-wrapper">
                <div class="navbar-item-prev">
                </div>
            </div>
        </div>
        
    </div>
</div>