home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.dashboard, name='dashboard_view'),
    path('test', views.test, name='test' ),
    path('register', views.register, name='register_view' ),
    path('login', views.login, name='login_view' ),
    path('registerUser', views.registerUser, name='registerUser' ),
    path('loginUser', views.loginUser, name='loginUser' ),
    path('logoutUser', views.logoutUser, name='logoutUser'),
    path('resetPassword', views.resetPassword, name="resetPassword_view"),
    path('twostepVerification', views.twostepVerification, name="twostepVerification_view"),
    path('forgotPassword', views.forgotPassword, name="forgotPassword_view"),
    path('verifyEmail', views.verifyEmail, name="verifyEmail_view"),
    path('activatePassword/<uidb64>/<token>', views.activatePassword, name='activatePassword'),
    path('emailVerification/<uidb64>/<token>', views.emailVerification, name='emailVerification'),
    path('insertConnectData', views.insertConnectData, name="insertConnectData"), 
    path('resendEmailVerification', views.resendEmailVerification, name="resendEmailVerification"),
    path('checkConnection', views.checkConnection, name="checkConnection"),
]

membership/urls.py
from django.urls import path
from . import views

app_name = 'membership'
urlpatterns = [
    path('checkout', views.checkout, name='checkout'),
    path('success', views.success, name='success'),
    path('cancel', views.cancel, name='cancel'),
    path('join', views.join, name='join'),
    path('billing', views.billing, name="billing_view"),
    path('billing_get_faq_data', views.billing_get_faq_data, name="billing_get_faq_data"),
    path('create_customer', views.create_customer, name="create_customer"),
    path('update_customer', views.update_customer, name="update_customer"),
    path('create_card', views.create_card, name="create_card"),
    path('get_card_list', views.get_card_list, name="get_card_list"),
    path('set_card_primary', views.set_card_primary, name="set_card_primary"),
    path('delete_card', views.delete_card, name="delete_card"),
    path('do_free_trial', views.do_free_trial, name="do_free_trial"),
    path('get_plan_status', views.get_plan_status, name="get_plan_status"),
    path('choose_plan', views.choose_plan, name="choose_plan"),
    path('get_current_subscription', views.get_current_subscription, name="get_current_subscription"),
    path('get_invoice_data', views.get_invoice_data, name="get_invoice_data"),
    path('get_customer_data', views.get_customer_data, name="get_customer_data"),
    path('get_customer_data_by_id', views.get_customer_data_by_id, name="get_customer_data_by_id"),
    path('get_subscription_data', views.get_subscription_data, name="get_subscription_data"),
]

wordyAI/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('user/', include('user.urls')),
    path('product/', include('product.urls')),
    path('test/', include('fileuploadtest.urls')),
    path('membership/', include('membership.urls')),
    path('admin_yuriimorigs_qweerrtrtty/', include('superAdmin.urls')),
    path('helpcenter/', include('helpcenter.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from wordyAI.constant import Role

# Create your models here.
class Users(models.Model):
    id = models.BigAutoField(primary_key=True, auto_created= True)
    email = models.CharField(max_length= 50)
    username = models.CharField(max_length=50)
    password = models.CharField(max_length=255)
    email_verification = models.BooleanField()
    avatar = models.ImageField(upload_to='images/')
    firstname = models.CharField(max_length=50)
    lastname = models.CharField(max_length=50)
    gender = models.IntegerField()
    gdpr = models.BooleanField()
    opt_url = models.CharField(max_length=250)
    opt_code = models.CharField(max_length=10)
    activate = models.BooleanField()
    role = models.IntegerField(default=Role.User.value)
    is_first = models.BooleanField(default = True)
    mobile = models.CharField(max_length=50, default='')
    phone = models.CharField(max_length=50, default='')
    address = models.CharField(max_length=50, default='')
    organization = models.CharField(max_length=255, default='')
    zipcode = models.CharField(max_length=50, default = '')
    state = models.CharField(max_length=50, default = '')
    country = models.CharField(max_length=50, default ='')
    language = models.CharField(max_length=50, default = '')
    timezone = models.CharField(max_length=50, default = '')
    currency = models.CharField(max_length=50, default = '')
    company = models.CharField(max_length=50, default = '')
    created_at = models.DateTimeField(auto_now_add = True, null= True)
    updated_at = models.DateTimeField(auto_now = True, null=True)

class ApiData(models.Model):
    id=models.BigAutoField(primary_key=True, auto_created=True)
    datatype = models.IntegerField()
    eshopType = models.IntegerField()
    applicationName = models.CharField(max_length = 255, default= '')
    api_url = models.CharField(max_length = 255)
    consumerKey = models.CharField(max_length = 255)
    consumerToken = models.CharField(max_length = 255)
    activate = models.BooleanField(default = True)
    users = models.ForeignKey(Users, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add = True, null= True)
    updated_at = models.DateTimeField(auto_now = True, null=True)

class OpenaiPrompt(models.Model):
    id=models.BigAutoField(primary_key=True, auto_created=True)
    teaser = models.TextField(default = '', null = True)
    hint = models.TextField(default = '', null = True)
    prompt = models.TextField(default = '', null = True)
    model = models.CharField(max_length = 30, null = True)
    key = models.CharField(max_length = 100, null = True)
    created_at = models.DateTimeField(auto_now_add = True, null= True)
    updated_at = models.DateTimeField(auto_now = True, null=True)
    

home/views.py
from base64 import urlsafe_b64decode, urlsafe_b64encode
from django.shortcuts import render, redirect
from django.contrib.auth.hashers import make_password, check_password
from django.http import JsonResponse
import json
from .models import Users, ApiData
from wordyAI.constant import *
from wordyAI.decorators import *
from .token import account_activation_token
from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_str
from django.core.mail import EmailMessage
from wordyAI.utils import *
from wordyAI.message import *
from woocommerce import API


def test(request):
    uidb64 = urlsafe_b64encode(force_bytes(1))
    print(uidb64)
    uidb64 = b'MQ=='
    uid = force_str(urlsafe_b64decode(uidb64))
    print(uid)
    return JsonResponse({})
# Create your views here.
@login_required
def dashboard(request):
    context = {}
    context = default_context(request, context)
    if request.session.get('is_login') == Role.Admin.value:
        return redirect('superAdmin:dashboard_view')
    else:
        return redirect('dashboard:analytics_view')
    
def register(request):
    context = {}
    return render(request, 'home/register.html', context)

def login(request):
    context = {}
    if 'is_login' in request.session:
        if request.session.get('is_login') == Role.Admin.value:
            return redirect('superAdmin:dashboard_view')
        else:
            return redirect('home:dashboard_view')
    else:
        return render(request, 'home/login.html', context)

def registerUser(request):
    res = {}
    data = json.loads(request.body)
    username = data['username']
    email = data['emailAddress']
    password = data['password']
    user_existance = Users.objects.filter(email = email).exists()

    if user_existance:
        res['message'] = USER_EXIST
        res['status'] = STATUS_FAIL
    else:
        user = Users.objects.create(username = username, email = email, password = make_password(password), activate = True, email_verification = False, gdpr = False, gender = Gender.NONE.value)        
        user.save()
        res['message'] = USER_REGISTER_SUCCESS
        res['status'] = STATUS_SUCCESS
        request.session['email'] = email
    return JsonResponse(res)

def loginUser(request):
    res = {}
    data = json.loads(request.body)
    username = data['username']
    password = data['password']
    rememberMe = data['rememberMe']
    ########## check user existance ###############
    user_existance = Users.objects.filter(username = username, activate = 1).exists()
    if user_existance:
        user = Users.objects.get(username = username)
        res = manipulateLogin(user,password, request)
        if rememberMe :
            request.session.set_expiry(60 * 60 * 24 * 365)
        else:
            request.session.set_expiry(0)
    else:
        res['message'] = USER_NOT_EXIST
        res['status'] = STATUS_FAIL
    
    return JsonResponse(res)

def manipulateLogin(user, password, request):
    res = {}
    if check_password(password, user.password):
        res['message'] = USER_LOGIN_SUCCESS
        res['status'] = STATUS_SUCCESS
        ####### register login  #######
        request.session['email'] = user.email
        request.session['is_login'] = user.role
        if user.role == Role.Admin.value:
            res['url'] = '/admin_yuriimorigs_qweerrtrtty'
        else:
            res['url'] = '/'
    else:
        res['message'] = PASSWORD_NOT_MATCH
        res['status'] = STATUS_FAIL

    return res

def logoutUser(request):
    res = {}
    del request.session['is_login']
    del request.session['email']
    res['message'] = USER_LOGOUT_SUCCESS
    res['status'] = STATUS_SUCCESS
    res['url'] = '/'
    return redirect('home:login_view')

def forgotPassword(request):
    if request.method == 'GET':
        context = {}
        return render(request, 'home/forgotPassword.html', context)
    else:
        res = {}
        data = json.loads(request.body)
        email = data['email']
        user_existance = Users.objects.filter(email = email).exists()
        if user_existance:
            res['message'] = USER_EMAIL_SENT
            res['status'] = STATUS_SUCCESS
            user = Users.objects.get(email = email)
            activatePasswordEmail(request, user, email)
        else:
            res['message'] = USER_NOT_EXIST
            res['status'] = STATUS_FAIL
        return JsonResponse(res)

def resetPassword(request):
    if request.method == 'POST':
        res = {}
        data = json.loads(request.body)
        password = data['password']
        user = Users.objects.get(email = request.session.get('email'))
        user.password = make_password(password)
        user.save()
        res['status'] = STATUS_SUCCESS
        return JsonResponse(res)
    else:
        context = {
            'email': request.session.get('email')
        }
        return render(request, 'home/resetPassword.html', context)

def verifyEmail(request):
    if 'email' in request.session:
        context = {
            'email': request.session.get('email')
        }
        email = request.session.get('email')
        user = Users.objects.get(email = email)
        activateEmailVerification(request, user, email)
        return render(request, 'home/verifyEmail.html', context)
    else:
        return redirect('home:register_view')

def twostepVerification(request):
    context = {}
    context = default_context(request, context)
    return render(request, 'home/twostepVerification.html', context)

def resendEmailVerification(request):
    res = {}
    if 'email' in request.session:
        context = {
            'email': request.session.get('email')
        }
        email = request.session.get('email')
        user = Users.objects.get(email = email)
        activateEmailVerification(request, user, email)
        res['status'] = STATUS_SUCCESS
        res['message'] = USER_EMAIL_SENT
    else:
        res['status'] = STATUS_FAIL
        res['message'] = NOT_REGISTERED_USER

def activateEmailVerification(request, user, to_email):
    print(to_email)
    mail_subject = MAIL_SUBJECT
    message = render_to_string('home/template_email_verification.html', {
        'user': user.username,
        'domain': get_current_site(request).domain,
        'uid': urlsafe_b64encode(force_bytes(user.id)),
        'token': account_activation_token.make_token(user),
        'protocol': 'https' if request.is_secure() else 'http'
    })
    email = EmailMessage(mail_subject, message, to=[to_email])
    email.send()

def activatePasswordEmail(request, user, to_email):
    print(to_email)
    mail_subject = MAIL_SUBJECT
    message = render_to_string('home/template_activate_password.html', {
        'user': user.username,
        'domain': get_current_site(request).domain,
        'uid': urlsafe_b64encode(force_bytes(user.id)),
        'token': account_activation_token.make_token(user),
        'protocol': 'https' if request.is_secure() else 'http'
    })
    email = EmailMessage(mail_subject, message, to=[to_email])
    email.send()

def activatePassword(request, uidb64, token):
    print(uidb64)
    try:
        uid = force_str(urlsafe_b64decode(uidb64[2:-1]))
        user = Users.objects.get(id=uid)
        
    except(TypeError, ValueError, OverflowError, Users.DoesNotExist):
        print('error')
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.save()
        request.session['email'] = user.email
        return redirect('home:resetPassword_view')
    else:
        return redirect('home:forgotPassword_view')
    
def emailVerification(request, uidb64, token):
    print(uidb64)
    try:
        uid = force_str(urlsafe_b64decode(uidb64[2:-1]))
        user = Users.objects.get(id=uid)
        
    except(TypeError, ValueError, OverflowError, Users.DoesNotExist):
        print('error')
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.email_verification = True
        user.save()
        request.session['email'] = user.email
        return redirect('home:login_view')
    else:
        return redirect('home:verifyEmail_view')

def insertConnectData(request):
    res = {}
    data = json.loads(request.body)
    email = request.session.get('email')
    user = Users.objects.get(email=email)
    applicationName = data['applicationName']
    apiUrl = data['apiUrl']
    consumerKey = data['consumerKey']
    consumerToken = data['consumerToken']
    category = data['category']
    eshopType = data['eshopType']

    apiData = ApiData(applicationName = applicationName, api_url = apiUrl, datatype = category, consumerKey = consumerKey,consumerToken = consumerToken, eshopType = eshopType, users = user)
    apiData.save()
    user.is_first = False
    user.save()
    res['status'] = 'success'

    return JsonResponse(res)    

def checkConnection(request):
    res = {}
    data = json.loads(request.body)
    apiUrl = data['apiUrl']
    consumerKey = data['consumerKey']
    consumerToken = data['consumerToken']

    wcapi = API(
        url= apiUrl,
        consumer_key= consumerKey,
        consumer_secret= consumerToken,
        version="wc/v3",
        timeout = 100
    )
    page = 1
    per_page = 1

    try:
        products = wcapi.get("products", params={"page": page, "per_page": per_page}).json()
        res['status'] = STATUS_SUCCESS
    except Exception as e:
        res['status'] = STATUS_FAIL
        res['message'] = INVALID_API
        print('----------------------------------------------------------')
        print(e)
    
    return JsonResponse(res)

templates/membership/billing.html
{% extends 'layouts/app.html' %}
{% load static %}

{% block style %}
    <link href="{% static 'assets/css/common.css' %}" rel="stylesheet" />
{% endblock style %}

{% block wrapper %}
<div class="page-wrapper">
    <div class="page-content">
        <div class="card p-4 mb-0">
            <div class="flex flex-column text-center">
                <p class="ft32 fw700 text-primary">Pricing Plans</p>
                <p class="ft16 text-secondary mb-2">All plans include 40+ advanced tools and features to boost your product.</p>
                <p class="ft16 text-secondary">Choose the best plan to fit your needs.</p>
                <div class="d-flex flex-row justify-content-center mb-2">
                    <img style="margin-left:280px;" src="{% static 'assets/images/data/arrow-down.png' %}"/>
                    <span class="color4 text-primary ft18 fw700 px-2 pt-1 rounded">Save up to 10%</span>
                </div>
                <div class="d-flex flex-row justify-content-center">
                    <p class="ft16 fw700 me-2 mb-0">Monthly</p>
                    <label class="switch me-2">
                        <input type="checkbox" id="modeCheck" checked>
                        <span class="slider round"></span>
                    </label>
                    <p class="ft16 fw700 mb-0">Annual</p>
                </div>
            </div>
            <div class="row mt-3">
                <div class="col-lg-4 col-12 mb-3">
                    <div class="d-flex flex-column align-items-center membershipBorder">
                        <img class="membershipImg mt-5" src="{% static 'assets/images/data/basic.png' %}"/>
                        <p class="ft32 fw700 text-primary mb-2">Basic</p>
                        <p>A simple start for everyone</p>
                        <div class="d-flex flex-row">
                            <p class="text-secondary pt10">$</p>
                            <p class="ft36 fw700 text-primary">10</p>
                            <p class="text-secondary pt20">/month</p>
                        </div>
                        <div>
                            <p class="text-secondary fw700 m-1">&#9711; 100 responses a month</p>
                            <p class="text-secondary fw700 m-1">&#9711; Unlimited forms and surveys</p>
                            <p class="text-secondary fw700 m-1">&#9711; Unlimited fields</p>
                            <p class="text-secondary fw700 m-1">&#9711; Basic form creation tools</p>
                        </div>
                        <div id="planBasic">
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-12 mb-3">
                    <div class="d-flex flex-column align-items-center membershipBorder">
                        <img class="membershipImg mt-5" src="{% static 'assets/images/data/standard.png' %}"/>
                        <p class="ft32 fw700 text-primary mb-2">Standard</p>
                        <p>For small to medium business</p>
                        <div class="d-flex flex-row">
                            <p class="text-secondary pt10">$</p>
                            <p class="ft36 fw700 text-primary">49</p>
                            <p class="text-secondary pt20">/month</p>
                        </div>
                        <div>
                            <p class="text-secondary fw700 m-1">&#9711; 100 responses a month</p>
                            <p class="text-secondary fw700 m-1">&#9711; Unlimited forms and surveys</p>
                            <p class="text-secondary fw700 m-1">&#9711; Unlimited fields</p>
                            <p class="text-secondary fw700 m-1">&#9711; Basic form creation tools</p>
                        </div>
                        <div id="planStandard">
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-12 mb-3">
                    <div class="d-flex flex-column align-items-center membershipBorder">
                        <img class="membershipImg mt-5" src="{% static 'assets/images/data/enterprise.png' %}"/>
                        <p class="ft32 fw700 text-primary mb-2">Enterprise</p>
                        <p>Solution for big organization</p>
                        <div class="d-flex flex-row">
                            <p class="text-secondary pt10">$</p>
                            <p class="ft36 fw700 text-primary">99</p>
                            <p class="text-secondary pt20">/month</p>
                        </div>
                        <div>
                            <p class="text-secondary fw700 m-1">&#9711; 100 responses a month</p>
                            <p class="text-secondary fw700 m-1">&#9711; Unlimited forms and surveys</p>
                            <p class="text-secondary fw700 m-1">&#9711; Unlimited fields</p>
                            <p class="text-secondary fw700 m-1">&#9711; Basic form creation tools</p>
                        </div>
                        <div id="planEnterprise">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="card p-4 my-0 bg-transparent" style="position:relative;">
            <p class="ft24 fw700 text-primary">Still not convinced? Start with a 14-day FREE trial!</p>
            <p class="text-secondary mb-4">You will get full access with all the feature for 14 days.</p>
            <div>
                <btn class="btn btn-primary px-4" onclick="doFreeTrial()">Start 14-Day Free Trial</btn>
            </div>  
            <img src="{% static 'assets/images/data/laptop-girl.png'%}" style="width:130px; position:absolute; top:20px; right:0px;">
        </div>
        <div class="card p-4 my-0">
            <p class="ft28 fw700 mt-4 mb-2 mx-auto text-primary">Pick a plan that works best for you </p> 
            <p class="mx-auto text-secondary">Stay cool, we have a 48-hour money-back guarantee!</p>
            <div class="custom-table-div1">
                <table class="table mb-0 table-striped table-bordered mt-2 custom-table1">
                    <thead>
                        <tr>
                            <th scope="col">FEATURES</th>
                            <th scope="col"><div class="d-flex flex-row justify-content-center">STARTER</div></th>
                            <th scope="col"><div class="d-flex flex-row justify-content-center">STANDARD</div></th>
                            <th scope="col"><div class="d-flex flex-row justify-content-center">ENTERPRISE</div></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>14-days free trial</td>
                            <td><div class="d-flex flex-row justify-content-center"><img src="{% static 'assets/images/data/check.png' %}"/></div></td>
                            <td><div class="d-flex flex-row justify-content-center"><img src="{% static 'assets/images/data/check.png' %}"/></div></td>
                            <td><div class="d-flex flex-row justify-content-center"><img src="{% static 'assets/images/data/check.png' %}"/></div></td>
                        </tr>
                        <tr>
                            <td>No uer limit</td>
                            <td><div class="d-flex flex-row justify-content-center"><img src="{% static 'assets/images/data/uncheck.png' %}"/></div></td>
                            <td><div class="d-flex flex-row justify-content-center"><img src="{% static 'assets/images/data/check.png' %}"/></div></td>
                            <td><div class="d-flex flex-row justify-content-center"><img src="{% static 'assets/images/data/check.png' %}"/></div></td>
                        </tr>
                        <tr>
                            <td>Product Support</td>
                            <td><div class="d-flex flex-row justify-content-center"><img src="{% static 'assets/images/data/uncheck.png' %}"/></div></td>
                            <td><div class="d-flex flex-row justify-content-center"><img src="{% static 'assets/images/data/uncheck.png' %}"/></div></td>
                            <td><div class="d-flex flex-row justify-content-center"><img src="{% static 'assets/images/data/check.png' %}"/></div></td>
                        </tr>
                        <tr>
                            <td></td>
                            <td><div class="d-flex flex-row justify-content-center"><button class="btn btn-primary px-3">Choose Plan</button></div></td>
                            <td><div class="d-flex flex-row justify-content-center"><button class="btn btn-primary px-3">Choose Plan</button></div></td>
                            <td><div class="d-flex flex-row justify-content-center"><button class="btn btn-primary px-3">Choose Plan</button></div></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="card p-4 my-0 bg-transparent" >
            <p class="ft32 fw700 mx-auto mt-5 text-primary">FAQ's</p>
            <p class="text-secondary mb-4 mx-auto">Let us help answer the most common questions.</p>
            <div id="faq_detail"></div>
            
        </div>
        <div id="backdrop">
            <div class="text-center-custom loading">
                <div class="spinner-border" role="status">
                    <span class="sr-only"></span>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock wrapper %}

{% block script %}
    <script src="{% static 'assets/js/product_download_status.js' %}"></script>
    <script src="{% static 'assets/js/billing.js' %}"></script>
{% endblock script%}

templates/membership/cancel.html
{% extends 'layouts/app.html' %}
{% load static %}

{% block style %}
    <link href="{% static 'assets/css/common.css' %}" rel="stylesheet" />
{% endblock style %}

{% block wrapper %}
<div class="page-wrapper">
    <div class="page-content">
        {% csrf_token %}
        <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <h1 class="display-4">Cloud Home Lab Premium</h1>
        </div>
          
        <div class="container">
            Ohhh... Something happened
        </div>
    </div>
</div>
{% endblock wrapper %}

{% block script %}
    <script src="{% static 'assets/js/product_download_status.js' %}"></script>
    <script src="{% static 'assets/js/membership.js' %}"></script>
{% endblock script%}

templates/membership/checkout.html
{% extends 'layouts/app.html' %}
{% load static %}

{% block style %}
    <link href="{% static 'assets/css/common.css' %}" rel="stylesheet" />
    <!-- Include Stripe.js at the bottom of your page -->
    <script src="https://js.stripe.com/v3/"></script>

{% endblock style %}

{% block wrapper %}
<div class="page-wrapper">
    <div class="page-content">
        {% csrf_token %}
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-4 order-md-2 mb-4">
                  <h4 class="d-flex justify-content-between align-items-center mb-3">
                    <span class="text-muted">Your cart</span>
                    <span class="badge badge-secondary badge-pill">1</span>
                  </h4>
                  <ul class="list-group mb-3">
                    <li class="list-group-item d-flex justify-content-between lh-condensed">
                      <div>
                        <h6 class="my-0">Cloud Home Lab Premium</h6>
                        <small class="text-muted">{{ membership | title }}</small>
                      </div>
                    </li>
                    <li class="list-group-item d-flex justify-content-between">
                      <span>Total (EUR)</span>
                      <strong>${{ final_dollar }}</strong>
                    </li>
                  </ul>
          
                  <div class="text-center pt-3">
          
                    <script src="https://js.stripe.com/v3/"></script>
          
                      <button id="checkout-button" data-secret="{{ session_id }}">
                        Checkout
                      </button>

                  </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock wrapper %}

{% block script %}
  <script src="{% static 'assets/js/product_download_status.js' %}"></script>
  <script src="{% static 'assets/js/membership.js' %}"></script>
{% endblock script%}

templates/membership/home.html
{% extends 'layouts/app.html' %}
{% load static %}

{% block style %}
    <link href="{% static 'assets/css/common.css' %}" rel="stylesheet" />
{% endblock style %}

{% block wrapper %}
<div class="page-wrapper">
    <div class="page-content">
        {% csrf_token %}

    </div>
</div>
{% endblock wrapper %}

{% block script %}
    <script src="{% static 'assets/js/product_download_status.js' %}"></script>
    <script src="{% static 'assets/js/membership.js' %}"></script>
{% endblock script%}

templates/membership/join.html
{% extends 'layouts/app.html' %}
{% load static %}

{% block style %}
    <link href="{% static 'assets/css/common.css' %}" rel="stylesheet" />
{% endblock style %}

{% block wrapper %}
<div class="page-wrapper">
    <div class="page-content">
        {% csrf_token %}
        <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <h1 class="display-4">Cloud Home Lab Premium</h1>
          </div>
          
          <div class="container">
            <div class="card-deck mb-3 text-center">
              <div class="card mb-4 shadow-sm">
                <div class="card-header">
                  <h4 class="my-0 font-weight-normal">Monthly</h4>
                </div>
                <div class="card-body">
                  <h1 class="card-title pricing-card-title">10€ <small class="text-muted">/ mo</small></h1>
                  <ul class="list-unstyled mt-3 mb-4">
                    <li>Premium Access</li>
                  </ul>
                  <a href="{% url 'membership:checkout' %}?membership=monthly"><button type="button" class="btn btn-lg btn-block btn-outline-primary">Get started</button></a>
                </div>
              </div>
              <div class="card mb-4 shadow-sm">
                <div class="card-header">
                  <h4 class="my-0 font-weight-normal">Yearly<small class="text-primary">  Save 20€!</small></h4>
                </div>
                <div class="card-body">
                  <h1 class="card-title pricing-card-title">100€ <small class="text-muted">/ yr</small></h1>
                  <ul class="list-unstyled mt-3 mb-4">
                    <li>Premium Access</li>
                  </ul>
                  <a href="{% url 'membership:checkout' %}?membership=yearly"><button type="button" class="btn btn-lg btn-block btn-primary">Get started</button></a>
                </div>
              </div>
            </div>
          </div>
    </div>
</div>
{% endblock wrapper %}

{% block script %}
  <script src="{% static 'assets/js/product_download_status.js' %}"></script>
{% endblock script%}