home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.dashboard, name='dashboard_view'),
    path('test', views.test, name='test' ),
    path('register', views.register, name='register_view' ),
    path('login', views.login, name='login_view' ),
    path('registerUser', views.registerUser, name='registerUser' ),
    path('loginUser', views.loginUser, name='loginUser' ),
    path('logoutUser', views.logoutUser, name='logoutUser'),
    path('resetPassword', views.resetPassword, name="resetPassword_view"),
    path('twostepVerification', views.twostepVerification, name="twostepVerification_view"),
    path('forgotPassword', views.forgotPassword, name="forgotPassword_view"),
    path('verifyEmail', views.verifyEmail, name="verifyEmail_view"),
    path('activatePassword/<uidb64>/<token>', views.activatePassword, name='activatePassword'),
    path('emailVerification/<uidb64>/<token>', views.emailVerification, name='emailVerification'),
    path('insertConnectData', views.insertConnectData, name="insertConnectData"), 
    path('resendEmailVerification', views.resendEmailVerification, name="resendEmailVerification"),
    path('checkConnection', views.checkConnection, name="checkConnection"),
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
    path('profile', views.profile, name='profile_view'),
    path('billing', views.billing, name='billing_view'),
    path('notification', views.notification, name='notification_view'),
    path('connections', views.connections, name='connections_view'),
    path('saveProfile', views.saveProfile, name='saveProfile'),
    path('security', views.security, name='security_view'),
    path('deactivate_account', views.deactivate_account, name='deactivate_account'),
    path('update_password', views.update_password, name='update_password'),
    path('admin/get_users', views.get_users, name='admin_get_users'),
    path('check_connection', views.check_connection, name='check_connection'),
    path('edit_shop', views.edit_shop, name='edit_shop'),
    path('update_shop', views.update_shop, name='update_shop'),
]

wordyAI/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('user/', include('user.urls')),
    path('product/', include('product.urls')),
    path('test/', include('fileuploadtest.urls')),
    path('membership/', include('membership.urls')),
    path('admin_yuriimorigs_qweerrtrtty/', include('superAdmin.urls')),
    path('helpcenter/', include('helpcenter.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/views.py
import json
from django.shortcuts import render, redirect
from wordyAI.utils import *
from wordyAI.constant import *
from wordyAI.decorators import *
from django.http import JsonResponse
from home.models import *
from wordyAI.message import *
from django.contrib.auth.hashers import make_password, check_password
from membership.models import *
from woocommerce import API
# Create your views here.

@admin_login_required
def get_users(request):
    context = {}
    context = default_context(request, context)
    return render(request, 'admin/user/user.html', context)

def test(request):
    context = {}
    context = default_context(request, context)
    return render(request, 'dashboard/analytics.html', context)

@login_required
def security(request):
    context = {}
    context = default_context(request, context)
    return render(request, 'user/security.html', context)

@login_required
def notification(request):
    context = {}
    context = default_context(request, context)
    return render(request, 'user/notification.html', context)

@login_required
def connections(request):
    context = {}
    context = default_context(request, context)
    return render(request, 'user/connections.html', context)

@login_required
def profile(request):
    context = {}
    context = default_context(request, context)
    return render(request, 'user/profile.html', context)

@login_required
def billing(request):
    context = {}
    context = default_context(request, context)
    stripeCustomers = StripeCustomer.objects.select_related('user').filter(user__email = request.session.get('email'))
    if stripeCustomers.count() == 1:
        for stripeCustomer in stripeCustomers:
            context['billingAddress'] = stripeCustomer.bill_address
            context['billingEmail'] = stripeCustomer.email
            context['city'] = stripeCustomer.city
            context['position'] = stripeCustomer.position
            context['mobileNumber'] = stripeCustomer.mobile
            context['state'] = stripeCustomer.state
            context['zipCode'] = stripeCustomer.zipcode
            context['country'] = stripeCustomer.country
            context['is_first'] = False
    else:
        context['is_first'] = True
    return render(request, 'user/billing.html', context)

def saveProfile(request):
    image = request.FILES.get('image', None)
    firstname = request.POST.get('firstname')
    company = request.POST.get('company')
    timezone = request.POST.get('timezone')
    lastname = request.POST.get('lastname')
    currency = request.POST.get('currency')

    user = Users.objects.get(email = request.session.get('email'))
    user.firstname = firstname
    user.company = company
    user.timezone = timezone
    user.lastname = lastname
    user.currency = currency
    
    if image is not None:
        user.avatar = image  
    user.save()

    return redirect('user:profile_view')

def deactivate_account(request):
    res = {}
    user = Users.objects.get(email = request.session.get('email'))
    user.activate = 0
    user.save()
    res['status'] = "success"
    res['message'] = DEACTIVATE_ACCOUNT_SUCCESS
    
    return JsonResponse(res)

def update_password(request):
    res = {}
    data = json.loads(request.body)
    currentPassword = data['currentPassword']
    newPassword = data['newPassword']
    user = Users.objects.get(email = request.session.get('email'))
    if check_password(currentPassword, user.password):
        user.password = make_password(newPassword)
        user.save()
        res['status'] = 'success'
        res['message']= PASSWORD_UPDATE_SUCCESS
    else:
        res['status'] = 'fail'
        res['message']= PASSWORD_NOT_CORRECT
    
    return JsonResponse(res)

def check_connection(request):
    res = {}
    email = request.session.get('email')
    apiData = ApiData.objects.select_related('users').filter(users__email = email).get()

    wcapi = API(
            url= apiData.api_url,
            consumer_key= apiData.consumerKey,
            consumer_secret= apiData.consumerToken,
            version="wc/v3",
            timeout = 100
        )
    try:
        products = wcapi.get("products", params={"page": 1, "per_page": 1}).json()
        res['status'] = STATUS_SUCCESS
        res['message'] = VALID_API

    except Exception as e:
        # Handle any errors from the Stripe API
        print(e)
        res['status'] = STATUS_FAIL
        res['message'] = INVALID_API
    return JsonResponse(res)

def edit_shop(request):
    res = {}
    email = request.session.get('email')
    apiData = ApiData.objects.select_related('users').filter(users__email = email).get()
    res['appName'] = apiData.applicationName
    res['apiUrl'] = apiData.api_url
    res['consumerKey'] = apiData.consumerKey
    res['consumerToken'] = apiData.consumerToken
    return JsonResponse(res)

def update_shop(request):
    res = {}
    data = json.loads(request.body)
    appName = data['appName']
    apiUrl = data['apiUrl']
    consumerKey = data['consumerKey']
    consumerToken = data['consumerToken']

    email = request.session.get('email')
    apiData = ApiData.objects.select_related('users').filter(users__email = email).get()
    apiData.applicationName = appName
    apiData.api_url = apiUrl
    apiData.consumerKey = consumerKey
    apiData.consumerToken = consumerToken
    apiData.save()

    res['status'] = STATUS_SUCCESS
    res['message'] = REQUEST_HANDLE_SUCCESS
    return JsonResponse(res)

templates/user/connections.html
{% extends 'layouts/app.html' %}
{% load static %}

{% block style %}
    <link href="{% static 'assets/css/common.css' %}" rel="stylesheet" />
{% endblock style %}

{% block wrapper %}
<div class="page-wrapper">
    <div class="page-content">
        <div class="p-4 d-flex flex-row">
            <a href="{% url 'user:profile_view' %}" class="tab-item-body">
                <div class="tab-item-icon"><i class='bx bx-user'></i>
                </div>
                <p class="tab-item-content">Account</p>
            </a>
            <a href="{% url 'user:security_view' %}" class="tab-item-body">
                <div class="tab-item-icon"><i class='bx bx-lock'></i>
                </div>
                <p class="tab-item-content">Security</p>
            </a>
            <a href="{% url 'user:billing_view' %}" class="tab-item-body">
                <div class="tab-item-icon"><i class='bx bx-file'></i>
                </div>
                <p class="tab-item-content">Billing</p>
            </a>
            <a href="{% url 'user:notification_view' %}" class="tab-item-body">
                <div class="tab-item-icon"><i class='bx bx-bell'></i>
                </div>
                <p class="tab-item-content">Notifications</p>
            </a>
            <a href="{% url 'user:connections_view' %}" class="tab-item-body tab-item-active">
                <div class="tab-item-icon"><i class='bx bx-link'></i>
                </div>
                <p class="tab-item-content">Connections</p>
            </a>
        </div>
        <div class="card p-4">
            <div class="row">
                <div class="col-md-6 col-12">
                    <p class="ft24 fwbold text-primary mb-4">Connected Accounts</p>
                    <div class="d-flex flex-column mb-4">
                        <div class="d-flex flex-row justify-content-between">
                            <div class="d-flex flex-row align-items-center">
                                <img class="imageDivSmall" src="{% static 'assets/images/data/brand-react-native.png' %}"/>
                                <p class="fwbold ft18 text-primary mb-0 ms-2">WooCommerce</p>
                            </div>
                            <div class="d-flex flex-row align-items-center">
                                <i class="bx bx-check text-primary-1 ft24 cursor-pointer me-3" onclick="checkConnection('WooCommerce')" ></i>
                                <i class="bx bx-edit-alt text-primary-1 ft24 cursor-pointer me-3" onclick="editShop('WooCommerce')"></i>
                                <label class="switch">
                                    <input type="checkbox" checked>
                                    <span class="slider round"></span>
                                </label>
                            </div>
                        </div>
                    </div>

                    <div class="d-flex flex-column mb-4">
                        <div class="d-flex flex-row justify-content-between">
                            <div class="d-flex flex-row align-items-center">
                                <img class="imageDivSmall" src="{% static 'assets/images/data/brand-angular.png' %}"/>
                                <p class="fwbold ft18 text-primary mb-0 ms-2">Magento 2</p>
                            </div>
                            <label class="switch">
                                <input type="checkbox" checked>
                                <span class="slider round"></span>
                            </label>
                        </div>
                    </div>

                    <div class="d-flex flex-column mb-4">
                        <div class="d-flex flex-row justify-content-between">
                            <div class="d-flex flex-row align-items-center">
                                <img class="imageDivSmall" src="{% static 'assets/images/data/brand-html5.png' %}"/>
                                <p class="fwbold ft18 text-primary mb-0 ms-2">Shopware 6</p>
                            </div>
                            <label class="switch">
                                <input type="checkbox" checked>
                                <span class="slider round"></span>
                            </label>
                        </div>
                    </div>

                    <div class="d-flex flex-column mb-4">
                        <div class="d-flex flex-row justify-content-between">
                            <div class="d-flex flex-row align-items-center">
                                <img class="imageDivSmall" src="{% static 'assets/images/data/brand-python.png' %}"/>
                                <p class="fwbold ft18 text-primary mb-0 ms-2">Shopify</p>
                            </div>
                            <label class="switch">
                                <input type="checkbox" checked>
                                <span class="slider round"></span>
                            </label>
                        </div>
                    </div>

                    <div class="d-flex flex-column mb-4">
                        <div class="d-flex flex-row justify-content-between">
                            <div class="d-flex flex-row align-items-center">
                                <img class="imageDivSmall" src="{% static 'assets/images/data/google.png' %}"/>
                                <p class="fwbold ft18 text-primary mb-0 ms-2">Google Analytics</p>
                            </div>
                            <label class="switch">
                                <input type="checkbox" checked>
                                <span class="slider round"></span>
                            </label>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <div class="modal fade" id="shop_update_modal" tabindex="-1" aria-hidden="true" data-backdrop="static" data-keyboard="false">
            <div class="modal-dialog modal-dialog-centered customModal">
                <div class="modal-content card">
                    <div class="d-flex flex-column align-items-center p-5">
                        <div class="mb-3 form-group w-100">
                            <p class="text-secondary mb-1 fw600">App Name</p>
                            <input type="text" class="form-control" name="appName" id="appName"/>
                        </div>
                        <div class="mb-3 form-group w-100">
                            <p class="text-secondary mb-1 fw600">Api Url</p>
                            <input type="text" class="form-control" name="apiUrl" id="apiUrl"/>
                        </div>
                        <div class="mb-3 form-group w-100">
                            <p class="text-secondary mb-1 fw600">Consumer Key</p>
                            <input type="text" class="form-control" name="consumerKey" id="consumerKey"/>
                        </div>
                        <div class="mb-3 form-group w-100">
                            <p class="text-secondary mb-1 fw600">Consumer Token</p>
                            <input type="text" class="form-control" name="consumerToken" id="consumerToken"/>
                        </div>
                        <div class="d-flex mt-3">
                            <button class="btn btn-primary px-4 mx-2" onclick="updateShop()"> Update </button>
                            <button class="btn btn-primary px-4 mx-2" onclick="updateCancel()"> Cancel </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div id="backdrop">
            <div class="text-center-custom loading">
                <div class="spinner-border" role="status">
                    <span class="sr-only"></span>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock wrapper %}

{% block script %}
    <script src="{% static 'assets/js/connections.js' %}"></script>
    <script src="{% static 'assets/js/product_download_status.js' %}"></script>
{% endblock script%}

templates/user/notification.html
{% extends 'layouts/app.html' %}
{% load static %}

{% block style %}
    <link href="{% static 'assets/css/common.css' %}" rel="stylesheet" />
{% endblock style %}

{% block wrapper %}
<div class="page-wrapper">
    <div class="page-content">
        <div class="p-4 d-flex flex-row">
            <a href="{% url 'user:profile_view' %}" class="tab-item-body">
                <div class="tab-item-icon"><i class='bx bx-user'></i>
                </div>
                <p class="tab-item-content">Account</p>
            </a>
            <a href="{% url 'user:security_view' %}" class="tab-item-body">
                <div class="tab-item-icon"><i class='bx bx-lock'></i>
                </div>
                <p class="tab-item-content">Security</p>
            </a>
            <a href="{% url 'user:billing_view' %}" class="tab-item-body">
                <div class="tab-item-icon"><i class='bx bx-file'></i>
                </div>
                <p class="tab-item-content">Billing</p>
            </a>
            <a href="{% url 'user:notification_view' %}" class="tab-item-body tab-item-active">
                <div class="tab-item-icon"><i class='bx bx-bell'></i>
                </div>
                <p class="tab-item-content">Notifications</p>
            </a>
            <a href="{% url 'user:connections_view' %}" class="tab-item-body">
                <div class="tab-item-icon"><i class='bx bx-link'></i>
                </div>
                <p class="tab-item-content">Connections</p>
            </a>
        </div>
        <div class="card p-4">
            <p class="ft24 fwbold text-primary">Recent Devices</p>
            <p class="ft12">We need permission from your browser to show notifications. Request Permission</p>
            <table class="table mb-0 table-striped table-bordered">
                <thead>
                    <tr>
                        <th scope="col">TYPE</th>
                        <th scope="col">EMAIL</th>
                        <th scope="col">BROWSER</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>New for you</td>
                        <td><input class="form-check-input" type="checkbox"></td>
                        <td><input class="form-check-input" type="checkbox"></td>
                    </tr>
                    <tr>
                        <td>Account activity</td>
                        <td><input class="form-check-input" type="checkbox"></td>
                        <td><input class="form-check-input" type="checkbox"></td>
                    </tr>
                    <tr>
                        <td>A new browser used to sign in</td>
                        <td><input class="form-check-input" type="checkbox"></td>
                        <td><input class="form-check-input" type="checkbox"></td>
                    </tr>
                    <tr>
                        <td>A new device is linked</td>
                        <td><input class="form-check-input" type="checkbox"></td>
                        <td><input class="form-check-input" type="checkbox"></td>
                    </tr>
                </tbody>
            </table>
            <p class="ft12 mt-3 fw600 text-primary">When sholud we send you notifications?</p>
            <input type="text" class="form-control" placeholder="Placeholder" name="placeholder" style="max-width:400px;" />
            <div class="d-flex flex-row mt-3">
                <button class="btn btn-primary me-3">Save Changes</button>
                <button class="btn btn-danger">Discard</button>
            </div>
        </div>
    </div>
</div>
{% endblock wrapper %}

{% block script %}
    <script src="{% static 'assets/js/users.js' %}"></script>
    <script src="{% static 'assets/js/product_download_status.js' %}"></script>
{% endblock script%}

templates/user/profile.html
{% extends 'layouts/app.html' %}
{% load static %}

{% block style %}
    <link href="{% static 'assets/css/common.css' %}" rel="stylesheet" />
    <link href="{% static 'assets/plugins/select2/css/select2.min.css' %}" rel="stylesheet" />
	<link href="{% static 'assets/plugins/select2/css/select2-bootstrap4.css' %}" rel="stylesheet" />
{% endblock style %}

{% block wrapper %}
<div class="page-wrapper">
    <div class="page-content">
        <!--breadcrumb-->

        <!--end breadcrumb-->
        <div class="row">
            <div class="container">
                <div class="main-body">
                    <div class="row">
                        <div class="p-4 d-flex flex-row">
                            <a href="{% url 'user:profile_view' %}" class="tab-item-body tab-item-active">
                                <div class="tab-item-icon"><i class='bx bx-user'></i>
                                </div>
                                <p class="tab-item-content">Account</p>
                            </a>
                            <a href="{% url 'user:security_view' %}" class="tab-item-body">
                                <div class="tab-item-icon"><i class='bx bx-lock'></i>
                                </div>
                                <p class="tab-item-content">Security</p>
                            </a>
                            <a href="{% url 'user:billing_view' %}" class="tab-item-body">
                                <div class="tab-item-icon"><i class='bx bx-file'></i>
                                </div>
                                <p class="tab-item-content">Billing</p>
                            </a>
                            <a href="{% url 'user:notification_view' %}" class="tab-item-body">
                                <div class="tab-item-icon"><i class='bx bx-bell'></i>
                                </div>
                                <p class="tab-item-content">Notifications</p>
                            </a>
                            <a href="{% url 'user:connections_view' %}" class="tab-item-body">
                                <div class="tab-item-icon"><i class='bx bx-link'></i>
                                </div>
                                <p class="tab-item-content">Connections</p>
                            </a>
                        </div>
                        <div class="card p-4">
                            <p class="ft24 fwbold text-primary">Profile Details</p>
                            <div class="d-flex flex-row">
                                <img src="{{avatar}}" alt="Admin" class="rounded-circle p-1 bg-primary" width="110">
                                <div class="d-flex flex-column ms-3">
                                    <div class="d-flex flex-row mt-3">
                                        <button class="btn btn-primary" onclick="imageClick()">Upload New Image</button>
                                        <button class="btn btn-primary ms-2 px-4" onclick="imageCancel()">Reset</button>
                                    </div>
                                    <p class="fw600 mt-3 mb-0" id="imageName">Allowed JPG, GIF or PNG. Max size of 800K</p>
                                </div>
                            </div>
                            <hr class="mb-3">
                            <form method="POST" action="{% url 'user:saveProfile' %}" enctype="multipart/form-data">
                                {% csrf_token %}
                                <input type="file" name="image" id="imageFile" hidden>
                                <div class="row">
                                    <div class="col-md-6 col-12">
                                        <div class="mb-3 form-group">
                                            <p class="text-primary mb-1 fw600">First Name</p>
                                            <input type="text" class="form-control" value="{{firstname}}" name="firstname" required/>
                                            <div class="invalid-feedback">
                                                Please enter a first name.
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-12">
                                        <div class="mb-3 form-group">
                                            <p class="text-primary mb-1 fw600">Last Name</p>
                                            <input type="text" class="form-control" value="{{lastname}}" name="lastname" required/>
                                            <div class="invalid-feedback">
                                                Please enter a last name.
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-12">
                                        <div class="mb-3 form-group">
                                            <p class="text-primary mb-1 fw600">Company</p>
                                            <input type="text" class="form-control" value="{{company}}" name="company" required/>
                                            <div class="invalid-feedback">
                                                Please enter a company.
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-12">
                                        <div class="mb-3 form-group">
                                            <p class="text-primary mb-1 fw600">Email</p>
                                            <input type="email" class="form-control" value="{{email}}" name="email" required>
                                            <div class="invalid-feedback">
                                                Please enter a valid email address.
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-12">
                                        <div class="mb-3 form-group">
                                            <p class="text-primary mb-1 fw600">Timezone</p>
                                            <select class="form-select mx-1" aria-label="Timezone" id="timezoneList" name="timezone">
                                                <option selected value=0>Select Timezone</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-12">
                                        <div class="mb-3 form-group">
                                            <p class="text-primary mb-1 fw600">Currency</p>
                                            <select class="form-select mx-1" aria-label="Currency" id="currencyList" name="currency">
                                                <option selected value=0>Select currency</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <div>
                                    <button class="btn btn-primary px-4" onclick="">Save Changes</button>
                                </div>
                            </form>
                        </div>
                        <div class="card p-4">
                            <p class="ft24 fwbold text-primary">Delete Account</p>
                            <div class="card p-4 color6">
                                <p class="ft16 mb-2 text-col1 fw600">Are you sure you want to delete your account?</p>
                                <p class="ft12 mb-0 text-col1">Once you delete your account, there is no going back. Please be certain.</p>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" id="deleteCheck" required>
                                <label class="form-check-label" for="gridCheck2">I confirm my account deactivation</label>
                            </div>
                            <div class="mt-3">
                                <button class="btn btn-danger px-4" onclick="deactivateAccount()">Deactivate Accounts</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
        </div>
        <!--end row-->
    </div>
</div>
{% endblock wrapper %}

{% block script %}
    <script src="{% static 'assets/js/profile.js' %}"></script>
    <script src="{% static 'assets/plugins/select2/js/select2.min.js' %}"></script>
    <script src="{% static 'assets/js/product_download_status.js' %}"></script>
    <script>
        {% comment %} $.ajax({
            url: "{% static 'assets/data/country.json' %}",
            dataType: "json",
            success: function(countryList) {
                countryList.forEach((data) => {
                    $('#countryList').append('<option value="'+data.name+'">'+ data.name + '</option>');    
                })
            }
        }); {% endcomment %}

        $.ajax({
            url: "{% static 'assets/data/timezone.json' %}",
            dataType: "json",
            success: function(timezoneList) {
                timezoneList.forEach((data) => {
                    $('#timezoneList').append('<option value="'+data.value+'">'+ data.text + '</option>');    
                })
            }
        });

        $.ajax({
            url: "{% static 'assets/data/currency.json' %}",
            dataType: "json",
            success: function(currencyList) {
                Object.entries(currencyList).forEach((data) => {
                    $('#currencyList').append('<option value="'+data[0]+'">'+ data[0] + '   (' + data[1].symbol +')' + '</option>');    
                })
            }
        });
    </script>
{% endblock script%}